services:
  - type: web
    name: fitpro-gym-manager
    runtime: dotnet
    plan: free
    buildCommand: dotnet build
    startCommand: dotnet run
    env: dotnet
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: fitpro-db
          property: connectionString

databases:
  - name: fitpro-db
    databaseName: fitpro
    plan: free
    ipAllowList: [] 