services:
  - type: web
    name: fitpro-gym-manager
    env: dotnet
    plan: free
    region: oregon
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/FitPro-Gym-Membership-Manager.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: fitpro-db
          property: connectionString

databases:
  - name: fitpro-db
    databaseName: fitpro
    plan: free
    ipAllowList: [] 